# AGNI configuration file
title = "Base config for structure calcs"

[planet]
    tmp_surf        = 2000.0
    instellation    = 1361.0
    albedo_b        = 0.18
    s0_fact         = 0.25
    zenith_angle    = 54.74
    surface_material= "res/surface_albedos/lunarmarebasalt.dat"
    albedo_s        = 0.0
    radius          = 8064561.9164
    mass            = 9.79e24
    flux_int        = 0.0
    turb_coeff      = 1.0e-2
    wind_speed      = 10.0
    star_Teff       = 3415.0

[files]
    input_sf        = "res/spectral_files/Dayspring/48/Dayspring.sf" #"greygas"
    input_star      = "blackbody"
    output_dir      = "out/"

[composition]
    p_surf          = 100.0
    p_top           = 1e-5
    metallicities   = {"C"=0.1, "S"=0.1, "O"=0.1}
    chemistry       = 1
    condensates     = []


[execution]
    clean_output    = false
    verbosity       = 1
    max_steps       = 70
    max_runtime     = 200
    num_levels      = 40
    continua        = true
    rayleigh        = false
    cloud           = false
    overlap_method  = "ee"
    grey_lw         = 5e-3
    grey_sw         = 2e-4
    real_gas        = false
    thermo_funct    = true
    sensible_heat   = true
    conduction      = false
    latent_heat     = false
    convection      = true
    convection_crit = "s"
    rainout         = false
    solution_type   = 3
    solver          = "newton"
    dx_max          = 200.0
    initial_state   = ["iso","2000"]
    linesearch      = 1
    easy_start      = false
    converge_atol   = 5.0
    converge_rtol   = 1.0e-2
    perturb_all     = true

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = false
    emission        = false
    albedo          = false
    mixing_ratios   = true
    animate         = true
    height          = true
    cloud           = false
