# AGNI configuration file
title = "Base config for structure calcs"

[planet]
    tmp_surf        = 1900.0
    instellation    = 13610.0 # #3.402500e6
    albedo_b        = 0.00
    s0_fact         = 0.25
    zenith_angle    = 54.74
    surface_material= "res/surface_albedos/lunarmarebasalt.dat"
    albedo_s        = 0.0
    radius          = 6e6 #5.0567e6
    mass            = 6e24 #2.986e24
    flux_int        = 0.0
    roughness       = 1.0e-2
    wind_speed      = 10.0
    star_Teff       = 3150.0 #3415.0

[files]
    input_sf        = "res/spectral_files/Dayspring/48/Dayspring.sf"
    #input_sf        = "greygas"
    #input_sf        = "res/spectral_files/Dayspring/16/Dayspring.sf"
    input_star      = "blackbody"
    output_dir      = "nogit_scratch/out/"

[composition]
    p_surf          = 1e4
    p_top           = 1e-3
    metallicities   = {"C"=1.0, "O"=10.0, "N"=0.3, "S"=0.1}  # temp mass fractions
    condensates     = []

[execution]
    clean_output    = true
    verbosity       = 1
    max_steps       = 52
    max_runtime     = 320
    num_levels      = 40
    solution_type   = 3
    solver          = "newton"
    dx_max          = 400.0
    dx_min          = 1e-10
    initial_state   = ["loglin","Teq"] #["loglin","1400", "str", "Teq"]
    linesearch      = 2
    easy_start      = true
    grey_start      = false
    converge_atol   = 1.0
    converge_rtol   = 1.0e-1
    perturb_all     = true

[physics]
    chemistry       = true
    continua        = true
    rayleigh        = true
    cloud           = false
    overlap_method  = "ee"
    grey_lw         = 5e-3
    grey_sw         = 2e-4
    real_gas        = true
    thermo_funct    = true
    sensible_heat   = false
    conduction      = false
    advection       = false
    latent_heat     = false
    convection      = true
    convection_crit = "s"
    rainout         = false
    oceans          = false

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = false
    emission        = false
    albedo          = false
    mixing_ratios   = true
    animate         = true
    height          = true
    cloud           = false
