# AGNI configuration file
title = "Base config for structure calcs"

[planet]
    tmp_surf        = 2500.0
    instellation    = 1e6 #3.402500e6
    albedo_b        = 0.18
    s0_fact         = 0.25
    zenith_angle    = 54.74
    surface_material= "res/surface_albedos/lunarmarebasalt.dat"
    albedo_s        = 0.0
    radius          = 6e6 #5.0567e6
    mass            = 6e24 #2.986e24
    flux_int        = 0.0
    roughness       = 1.0e-2
    wind_speed      = 10.0
    star_Teff       = 3415.0

[files]
    input_sf        = "res/spectral_files/Dayspring/48/Dayspring.sf" #
    input_star      = "blackbody"
    output_dir      = "out/"

[composition]
    p_surf          = 100.0
    p_top           = 1e-5
    metallicities   = {"C"=0.01, "S"=0.1, "O"=0.1}  # mass fraction
    condensates     = []

[execution]
    clean_output    = false
    verbosity       = 1
    max_steps       = 50
    max_runtime     = 200
    num_levels      = 35
    solution_type   = 3
    solver          = "newton"
    dx_max          = 100.0
    initial_state   = ["loglin","800"]
    linesearch      = 1
    easy_start      = true
    grey_start      = false
    converge_atol   = 1.0
    converge_rtol   = 1.0e-2
    perturb_all     = true

[physics]
    chemistry       = true
    continua        = true
    rayleigh        = false
    cloud           = false
    overlap_method  = "ee"
    grey_lw         = 5e-3
    grey_sw         = 2e-4
    real_gas        = false
    thermo_funct    = true
    sensible_heat   = true
    conduction      = false
    advection       = false
    latent_heat     = false
    convection      = true
    convection_crit = "l"
    rainout         = false
    oceans          = false

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = false
    emission        = false
    albedo          = false
    mixing_ratios   = true
    animate         = true
    height          = true
    cloud           = false
