# AGNI configuration file
title = "Chemistry and condensation together"

[planet]
    tmp_surf        = 1500.0
    instellation    = 1500.0
    albedo_b        = 0.0
    s0_fact         = 0.375
    zenith_angle    = 48.19
    surface_material= "greybody"
    albedo_s        = 0.2
    radius          = 6.37e6
    gravity         = 9.81
    flux_int        = 0.0
    roughness       = 1.0e-2
    wind_speed      = 10.0
    skin_k          = 2.0
    skin_d          = 0.01
    tmp_magma       = 1700.0
    star_Teff       = 5000.0

[files]
    input_sf        = "res/spectral_files/Dayspring/48/Dayspring.sf"
    input_star      = "blackbody"
    output_dir      = "out/"

[composition]
    p_surf          = 7000.0
    p_top           = 1e-4
    vmr_dict        = { H2O=0.5, CO2=0.35, CH4=0.1, N2=0.05}
    condensates     = ["H2O"]

[execution]
    clean_output    = true
    verbosity       = 1
    max_steps       = 300
    max_runtime     = 400
    num_levels      = 45
    solution_type   = 3
    solver          = "newton"
    dx_max          = 300.0
    initial_state   = ["iso","1500"]
    linesearch      = 1
    easy_start      = true
    grey_start      = false
    converge_atol   = 1.0
    converge_rtol   = 1.0e-2
    perturb_all     = true

[physics]
    chemistry       = true
    continua        = true
    rayleigh        = true
    cloud           = false
    overlap_method  = "ee"
    real_gas        = false
    thermo_funct    = true
    sensible_heat   = true
    advection       = false
    conduction      = true
    convection      = true
    convection_crit = "l"
    grey_lw         = 5e-2
    grey_sw         = 1e-2
    rainout         = true
    oceans          = true
    latent_heat     = false


[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = true
    emission        = true
    albedo          = true
    mixing_ratios   = true
    animate         = true
    height          = true
    cloud           = true
