# AGNI configuration file
title = "Line-by-line validation tests"

[planet]
    tmp_surf        = 400.0
    instellation    = 0.0
    albedo_b        = 0.0
    s0_fact         = 1.0
    zenith_angle    = 0.0
    surface_material= "greybody"
    albedo_s        = 0.0
    radius          = 6.6e6
    gravity         = 20
    flux_int        = 0.0
    roughness       = 1.0e-2
    wind_speed      = 2.0

[files]
    input_sf        = "out/ee/runtime.sf" #"res/spectral_files/Dayspring/4096/Dayspring.sf"
    input_star      = "" # "res/stellar_spectra/sun.txt"
    output_dir      = "out/ro/"
    rfm_parfile     = "res/parfiles/h2o-co2_800-9000.par"

[composition]
    p_surf          = 270.0
    p_top           = 1e-6
    vmr_dict        = { H2O = 0.9, CO2=0.1 }
    condensates     = []

[execution]
    clean_output    = false
    verbosity       = 2
    max_steps       = 20000
    max_runtime     = 400
    num_levels      = 100
    solution_type   = 1
    solver          = ""
    dx_max          = 400.0
    initial_state   = ["dry", "sat", "H2O"]
    linesearch      = 0
    easy_start      = false
    grey_start      = false
    converge_atol   = 1.0e-2
    converge_rtol   = 1.0e-3
    rfm_wn_min      = 1000.0
    rfm_wn_max      = 6000.0
    perturb_all     = false

[physics]
    chemistry       = 0
    continua        = false
    rayleigh        = false
    cloud           = false
    overlap_method  = "ro"
    real_gas        = false
    thermo_funct    = true
    sensible_heat   = false
    conduction      = true
    latent_heat     = false
    convection      = false
    convection_crit = "s"
    rainout         = false

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = false
    emission        = false
    albedo          = false
    mixing_ratios   = false
    animate         = false
    height          = false
    cloud           = false
