# AGNI configuration file
title = "Test setting composition by metallicity"

[planet]
    tmp_surf        = 1900.0
    instellation    = 1e5
    albedo_b        = 0.0
    s0_fact         = 0.6652
    zenith_angle    = 60.0
    surface_material= "res/surface_albedos/basalttuff.dat"
    radius          = 1.1959e7
    gravity         = 22.304
    flux_int        = 0.0
    roughness       = 1.0e-2
    wind_speed      = 2.0

[files]
    input_sf        = "res/spectral_files/Honeyside/48/Honeyside.sf"
    input_star      = "res/stellar_spectra/hd97658.txt"
    output_dir      = "out/"

[composition]
    p_surf          = 5000.0
    p_top           = 1e-5
    metallicities   = {"C"=1.0, "S"=1.0, "O"=1.0, "N"=1.0}  # by mass fraction relative to H (solar is 0.01)
    chemistry       = 1
    condensates     = []

[execution]
    clean_output    = false
    verbosity       = 1
    max_steps       = 20000
    max_runtime     = 400
    num_levels      = 40
    continua        = true
    rayleigh        = true
    cloud           = false
    overlap_method  = "ee"
    real_gas        = false
    thermo_funct    = true
    sensible_heat   = false
    conduction      = true
    latent_heat     = true
    convection      = true
    convection_crit = "l"
    rainout         = false
    solution_type   = 3
    solver          = "newton"
    dx_max          = 100.0
    initial_state   = ["loglin", "800"]
    linesearch      = 1
    easy_start      = false
    converge_atol   = 1.0e-2
    converge_rtol   = 1.0e-3
    perturb_all     = true

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = true
    emission        = true
    albedo          = true
    mixing_ratios   = true
    animate         = true
    height          = true
    cloud           = false
