# AGNI configuration file
title = "Roughly 55 Cancri e @ fO2=IW"

[planet]
    tmp_surf        = 2700.0
    instellation    = 3.3231e6
    albedo_b        = 0.0
    s0_fact         = 1.0 #0.6652
    zenith_angle    = 0.0 #60.0
    surface_material= "res/surface_albedos/basalttuff.dat"
    radius          = 1.1959e7
    gravity         = 22.304
    flux_int        = 0.0
    roughness       = 1.0e-2
    wind_speed      = 2.0

[files]
    input_sf        = "res/spectral_files/Dayspring/48/Dayspring.sf"
    input_star      = "res/stellar_spectra/hd97658.txt"
    output_dir      = "out/"

[composition]
    p_top           = 1e-7
    p_dict          = {H2O = 0.308,CO2 = 15.516,N2  = 16.065,H2  = 0.691,CO  = 231.415    }
    condensates     = []

[execution]
    clean_output    = false
    verbosity       = 1
    max_steps       = 20000
    max_runtime     = 400
    num_levels      = 45
    solution_type   = 3
    solver          = "newton"
    dx_max          = 400.0
    initial_state   = ["iso","2000"] #["ncdf", "out/atm.nc"]
    linesearch      = 0
    easy_start      = false
    grey_start      = false
    converge_atol   = 1.0e-2
    converge_rtol   = 1.0e-3
    perturb_all     = false

[physics]
    chemistry       = true
    continua        = true
    rayleigh        = true
    cloud           = false
    overlap_method  = "ee"
    real_gas        = false
    thermo_funct    = true
    sensible_heat   = false
    conduction      = true
    advection       = false
    latent_heat     = true
    convection      = true
    convection_crit = "l"
    rainout         = false

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = true
    emission        = true
    albedo          = true
    mixing_ratios   = true
    animate         = true
    height          = true
    cloud           = false
