# AGNI configuration file
title = "L 98-59 d"

[planet]
    tmp_surf        = 2500.0
    instellation    = 6818.61
    albedo_b        = 0.0
    s0_fact         = 0.25
    zenith_angle    =  54.74
    surface_material= "res/surface_albedos/lunarmarebasalt.dat"
    albedo_s        = 0.0
    radius          = 8064561.9164
    mass            = 9.79e24
    flux_int        = 0.58586427102
    roughness       = 1.0e-2
    wind_speed      = 10.0
    star_Teff       = 3415.0

[files]
    input_sf        = "res/spectral_files/Honeyside/48/Honeyside.sf"
    input_star      = "blackbody" #"res/stellar_spectra/l-98-59.txt"
    output_dir      = "out/"

[composition]
    p_surf          = 32.89e3
    p_top           = 1e-4
    vmr_dict        = { H2=0.8, H2S=0.15, H2O=0.05 }
    condensates     = []

[execution]
    clean_output    = true
    verbosity       = 1
    max_steps       = 200
    max_runtime     = 400
    num_levels      = 38
    solution_type   = 3
    solver          = "newton"
    dx_max          = 500.0
    initial_state   = ["loglin","1000"]
    linesearch      = 2
    easy_start      = false
    grey_start      = false
    converge_atol   = 1e-1
    converge_rtol   = 1e-2
    perturb_all     = false

[physics]
    chemistry       = false
    continua        = true
    rayleigh        = true
    cloud           = false
    overlap_method  = "ee"
    real_gas        = true
    thermo_funct    = true
    sensible_heat   = true
    advection       = false
    conduction      = true
    latent_heat     = true
    convection      = true
    convection_crit = "s"
    rainout         = false

[plots]
    at_runtime      = true
    temperature     = true
    fluxes          = true
    contribution    = true
    emission        = true
    albedo          = true
    mixing_ratios   = true
    animate         = false
    height          = false
    cloud           = false
